#! /bin/bash

echo "Bash version ${BASH_VERSION}..."

conda update --all -n base

for env in $(conda env list | cut -d" " -f1 | tail -n+4)
do 
    echo      
    echo      
    echo      
    echo  "*******************************************************************"
    echo  $env $env $env $env $env $env $env $env
    echo  "*******************************************************************"
    conda update --all -y -n $env
    conda env export -n $env > ~/Admin/CondaAdmin/$env.yml
    conda list -n $env > ~/Admin/CondaAdmin/$env.txt
done

# cp -v ~/Admin/CondaAdmin/base.* ~/AEMpyX/environment/linux/ubuntu22.04/
# cp -v ~/Admin/CondaAdmin/base.* ~/Py4MT/environment/
# cp -v ~/Admin/CondaAdmin/base.* ~/JacoPyAn/environment/
#
# cp -v ~/Admin/CondaAdmin/JacoPyAn8.* ~/JacoPyAn/environment/
# cp -v ~/Admin/CondaAdmin/AEMpyX*.* ~/AEMpyX/environment/linux/ubuntu22.04/
# cp -v ~/Admin/CondaAdmin/Py4MT*.* ~/AEMpyX/environment/linux/ubuntu22.04/

