#! /bin/bash

conda env export -n base > ~/Admin/Anaconda/base.yml
conda env export -n Gymli >~/Admin/Anaconda/Gymli.yml
conda env export -n Hippy >~/Admin/Anaconda/Hippy.yml
conda env export -n jif3d >~/Admin/Anaconda/jif3d.yml
conda env export -n EM38 >~/Admin/Anaconda/EM38.yml
conda env export -n EM39 >~/Admin/Anaconda/EM39.yml
conda env export -n EM310 >~/Admin/Anaconda/EM310.yml
conda env export -n GemGIS >~/Admin/Anaconda/GemGIS.yml


conda list  -n base > ~/Admin/Anaconda/base.txt
conda list  -n Gymli >~/Admin/Anaconda/Gymli.txt
conda list  -n Hippy >~/Admin/Anaconda/Hippy.txt
conda list  -n jif3d >~/Admin/Anaconda/jif3d.txt
conda list  -n EM38 >~/Admin/Anaconda/EM38.txt
conda list  -n EM39 >~/Admin/Anaconda/EM39.txt
conda list  -n EM310 >~/Admin/Anaconda/EM310.txt
conda list  -n GemGIS >~/Admin/Anaconda/GemGIS.txt


cp -v ~/Admin/Anaconda/EM*.* ~/Admin/Anaconda/base*  ~/AEMpyX/environment/
cp -v ~/Admin/Anaconda/EM*.* ~/Admin/Anaconda/base* ~/Py4MT/environment/


