#! /bin/bash
echo "*********** base"
conda update conda -y -n base
conda update --all -y -n base

echo "*********** EM38"
conda update --all -y -n EM38
echo "*********** EM39"
conda update --all -y -n EM39
echo "*********** EM310"
conda update --all -y -n EM310
echo "*********** jif3d"
conda update --all -y -n jif3d
# echo "*********** Fenics"
#Rconda update --all -y -n Fenics
#echo "*********** EarthEngine"
#conda update --all -y -n EarthEngine
echo "*********** Gymli"
conda update --all -y -n Gymli
echo "*********** Hippy"
conda update --all -y -n Hippy
echo "*********** EM39"
conda update --all -y -n EM39
echo "*********** GemGIS"
conda update --all -y -n GemGIS

conda_export_all
