#! /bin/bash

echo "Bash version ${BASH_VERSION}..."


conda update conda -y -n base

for env in $(conda env list | cut -d" " -f1 | tail -n+4)
do 
    echo      
    echo      
    echo      
    echo  "*******************************************************************"
    echo  $env $env $env $env $env $env $env $env
    echo  "*******************************************************************"
#     conda update --all -y -n $env
    conda env export -n $env > ./$env.yml
    conda list -n $env > ./$env.txt
done
