#! /bin/bash

conda env export -n base > ~/Admin/Anaconda/base.yml
conda env export -n EM >~/Admin/Anaconda/EM.yml
#conda env export -n SimPEG >~/Admin/Anaconda/SimPEG.yml
# conda env export -n Fenics >~/Admin/Anaconda/Fenics.yml
#conda env export -n EarthEngine >~/Admin/Anaconda/EarthEngine.yml
conda env export -n Gymli >~/Admin/Anaconda/Gymli.yml
conda env export -n Hippy >~/Admin/Anaconda/Hippy.yml
#conda env export -n RAFTA >~/Admin/Anaconda/RAFTA.yml
conda env export -n EM39 >~/Admin/Anaconda/EM39.yml
conda env export -n EM310 >~/Admin/Anaconda/EM310.yml
conda env export -n GemGIS >~/Admin/Anaconda/GemGIS.yml


conda list  -n base > ~/Admin/Anaconda/base.txt
conda list  -n EM >~/Admin/Anaconda/EM.txt
#conda list  -n SimPEG >~/Admin/Anaconda/SimPEG.txt
#conda list  -n Fenics >~/Admin/Anaconda/Fenics.txt
#conda list  -n EarthEngine >~/Admin/Anaconda/EarthEngine.txt
conda list  -n Gymli >~/Admin/Anaconda/Gymli.txt
conda list  -n Hippy >~/Admin/Anaconda/Hippy.txt
#conda list  -n RAFTA >~/Admin/Anaconda/RAFTA.txt
conda list  -n EM39 >~/Admin/Anaconda/EM39.txt
conda list  -n EM310 >~/Admin/Anaconda/EM310.txt
conda list  -n GemGIS >~/Admin/Anaconda/GemGIS.txt


cp -v ~/Admin/Anaconda/EM*.* ~/Admin/Anaconda/base*  ~/AEMpyX/environment/
cp -v ~/Admin/Anaconda/EM*.* ~/Admin/Anaconda/base* ~/Py4MT/environment/


