#! /bin/bash 

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/vrath/.Miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/vrath/.Miniconda/etc/profile.d/conda.sh" ]; then
        . "/home/vrath/.Miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/vrath/.Miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
